export const strategyParamKeys: Record<string, string[]> = {
  orb: [
    "or_minutes",
    "sl_pct",
    "tp_pct",
    "max_positions",
    "timeframe",
    "trade_size",
    "cooldown_bars",
    "enable_shorts",
  ],
  sr_breakout: [
    "breakout_buffer_pct",
    "pivot_type",
    "sl_pct",
    "tp_pct",
    "max_positions",
    "trade_size",
  ],
  "52w_chaser": [
    "entry_threshold_pct",
    "sl_pct",
    "tp_pct",
    "enable_trailing_stop",
    "trailing_stop_pct",
    "trailing_activation_pct",
    "max_holding_days",
    "cooldown_days",
    "trade_size",
    "enable_filters",
  ],
  "52w_target": [
    "entry_threshold_pct",
    "sl_pct",
    "trailing_stop_pct",
    "max_holding_days",
    "cooldown_days",
    "trade_size",
  ],
  ema_cross: [
    "ema_fast_period",
    "ema_slow_period",
    "sl_pct",
    "tp_pct",
    "timeframe",
    "trade_size",
    "enable_shorts",
    "cooldown_bars",
  ],
};

export function getStrategyDefaults(strategyId: string): Record<string, any> {
  const defaults: Record<string, any> = {
    orb: {
      or_minutes: 45,
      timeframe: "5",
      stop_loss_pct: 0.5,
      take_profit_pct: 1.5,
      trade_size: 100,
      cooldown_bars: 3,
      enable_shorts: false,
      max_positions: 5,
    },
    sr_breakout: {
      pivot_type: "classic",
      breakout_buffer_pct: 0.1,
      stop_loss_pct: 0.5,
      take_profit_pct: 1.5,
      trade_size: 100,
      max_positions: 3,
    },
    "52w_chaser": {
      entry_threshold_pct: 3.0,
      stop_loss_pct: 3.0,
      take_profit_pct: 5.0,
      enable_trailing_stop: false,
      trailing_stop_pct: 3.0,
      trailing_activation_pct: 2.0,
      max_holding_days: 30,
      cooldown_days: 30,
      trade_size: 100,
      enable_filters: false,
    },
    "52w_target": {
      entry_threshold_pct: 2.0,
      stop_loss_pct: 2.0,
      trailing_stop_pct: 0.5,
      max_holding_days: 15,
      cooldown_days: 7,
      trade_size: 100,
    },
    ema_cross: {
      ema_fast_period: 9,
      ema_slow_period: 21,
      stop_loss_pct: 0.5,
      take_profit_pct: 1.5,
      timeframe: "5",
      trade_size: 100,
      enable_shorts: false,
      cooldown_bars: 3,
    },
  };
  return defaults[strategyId] || {};
}
