"""drop min_rr_ratio from strategy_configs

Revision ID: c8fe5a34f1b5
Revises: 9fb7dcf4d187
Create Date: 2026-05-05 23:41:43.953705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8fe5a34f1b5'
down_revision: Union[str, Sequence[str], None] = '9fb7dcf4d187'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_configs', schema=None) as batch_op:
        batch_op.drop_column('min_rr_ratio')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('strategy_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_rr_ratio', sa.FLOAT(), server_default=sa.text('(2.0)'), nullable=True))

    # ### end Alembic commands ###
