"""add max_daily_loss_pct to bot_configs

Revision ID: 9fb7dcf4d187
Revises: k0e1f2g3h4b5
Create Date: 2026-05-05 22:51:48.117513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb7dcf4d187'
down_revision: Union[str, Sequence[str], None] = 'k0e1f2g3h4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bot_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_daily_loss_pct', sa.Float(), nullable=True))

    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversations_uuid'), ['uuid'], unique=True)

    with op.batch_alter_table('screeners', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_screener', ['user_id', 'name'])

    with op.batch_alter_table('stock_52week_touches', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_stock_52week_touches_symbol_touched_date'))
        batch_op.create_index('ix_stock_52week_touches_symbol_touched_date', ['symbol', 'touched_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_52week_touches', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_52week_touches_symbol_touched_date')
        batch_op.create_index(batch_op.f('ix_stock_52week_touches_symbol_touched_date'), ['symbol', 'touched_date'], unique=1)
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    with op.batch_alter_table('screeners', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_screener', type_='unique')

    with op.batch_alter_table('chat_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_conversations_uuid'))

    with op.batch_alter_table('bot_configs', schema=None) as batch_op:
        batch_op.drop_column('max_daily_loss_pct')

    # ### end Alembic commands ###
