"""add broker unique constraint

Revision ID: 127ccb4ed22e
Revises: e770cdca44e6
Create Date: 2026-03-27 22:42:16.119523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '127ccb4ed22e'
down_revision: Union[str, Sequence[str], None] = 'e770cdca44e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_connections', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_broker_name_user', ['broker_name', 'user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('broker_connections', schema=None) as batch_op:
        batch_op.drop_constraint('uq_broker_name_user', type_='unique')

    # ### end Alembic commands ###
