import type { Meta, StoryObj } from "@storybook/react";
import { MantineProvider } from "@mantine/core";
import { StrategiesList } from "./StrategiesList";
import type { StrategyConfig } from "../../types/strategies";

const meta: Meta<typeof StrategiesList> = {
  title: "Design System/Strategies/List",
  component: StrategiesList,
  tags: ["autodocs"],
  decorators: [
    (Story) => (
      <MantineProvider>
        <Story />
      </MantineProvider>
    ),
  ],
  parameters: {
    layout: "fullscreen",
  },
};

export default meta;
type Story = StoryObj<typeof StrategiesList>;

const mockTemplates: StrategyConfig[] = [
  {
    id: 1,
    name: "ORB Bullish Template",
    strategy_type: "ORB_Bullish",
    parent_id: null,
    is_template: true,
    is_active: true,
    is_default: false,
    description: "ORB bullish template",
    or_minutes: 15,
    sl_pct: 0.5,
    tp_pct: 1.0,
    min_or_range_pct: 0.3,
    max_or_range_pct: 2.0,
    max_positions: 3,
    max_capital_per_trade_pct: 20,
    max_daily_loss_pct: 5,
    max_total_exposure_pct: 50,
    risk_per_trade_pct: 2,
    min_trade_value: 5000,
    max_trade_value: 100000,
    cooldown_minutes: 30,
    max_distance_from_or_pct: 1.5,
    brokerage_pct: 0.05,
    min_brokerage: 20,
    stt_pct: 0.001,
    exchange_pct: 0.0003,
    sebi_pct: 0.0001,
    stamp_pct: 0.0003,
    gst_pct: 0.18,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 2,
    name: "ORB Bearish Template",
    strategy_type: "ORB_Bearish",
    parent_id: null,
    is_template: true,
    is_active: true,
    is_default: false,
    description: "ORB bearish template",
    or_minutes: 15,
    sl_pct: 0.5,
    tp_pct: 1.0,
    min_or_range_pct: 0.3,
    max_or_range_pct: 2.0,
    max_positions: 3,
    max_capital_per_trade_pct: 20,
    max_daily_loss_pct: 5,
    max_total_exposure_pct: 50,
    risk_per_trade_pct: 2,
    min_trade_value: 5000,
    max_trade_value: 100000,
    cooldown_minutes: 30,
    max_distance_from_or_pct: 1.5,
    brokerage_pct: 0.05,
    min_brokerage: 20,
    stt_pct: 0.001,
    exchange_pct: 0.0003,
    sebi_pct: 0.0001,
    stamp_pct: 0.0003,
    gst_pct: 0.18,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

const mockStrategies: StrategyConfig[] = [
  {
    id: 10,
    name: "Default Bullish Strategy",
    strategy_type: "ORB_Bullish",
    parent_id: 1,
    is_template: false,
    is_active: true,
    is_default: true,
    description: "Default bullish strategy",
    or_minutes: 15,
    sl_pct: 0.5,
    tp_pct: 1.0,
    min_or_range_pct: 0.3,
    max_or_range_pct: 2.0,
    max_positions: 3,
    max_capital_per_trade_pct: 20,
    max_daily_loss_pct: 5,
    max_total_exposure_pct: 50,
    risk_per_trade_pct: 2,
    min_trade_value: 5000,
    max_trade_value: 100000,
    cooldown_minutes: 30,
    max_distance_from_or_pct: 1.5,
    brokerage_pct: 0.05,
    min_brokerage: 20,
    stt_pct: 0.001,
    exchange_pct: 0.0003,
    sebi_pct: 0.0001,
    stamp_pct: 0.0003,
    gst_pct: 0.18,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: 11,
    name: "Aggressive Bullish",
    strategy_type: "ORB_Bullish",
    parent_id: 1,
    is_template: false,
    is_active: true,
    is_default: false,
    description: "Aggressive bullish variation",
    or_minutes: 15,
    sl_pct: 0.3,
    tp_pct: 1.5,
    min_or_range_pct: 0.3,
    max_or_range_pct: 2.0,
    max_positions: 5,
    max_capital_per_trade_pct: 25,
    max_daily_loss_pct: 7,
    max_total_exposure_pct: 60,
    risk_per_trade_pct: 3,
    min_trade_value: 5000,
    max_trade_value: 150000,
    cooldown_minutes: 15,
    max_distance_from_or_pct: 2.0,
    brokerage_pct: 0.05,
    min_brokerage: 20,
    stt_pct: 0.001,
    exchange_pct: 0.0003,
    sebi_pct: 0.0001,
    stamp_pct: 0.0003,
    gst_pct: 0.18,
    created_at: "2024-01-02T00:00:00Z",
    updated_at: "2024-01-02T00:00:00Z",
  },
  {
    id: 12,
    name: "Conservative Bearish",
    strategy_type: "ORB_Bearish",
    parent_id: 2,
    is_template: false,
    is_active: false,
    is_default: false,
    description: "Conservative bearish variation",
    or_minutes: 30,
    sl_pct: 0.8,
    tp_pct: 0.8,
    min_or_range_pct: 0.5,
    max_or_range_pct: 1.5,
    max_positions: 2,
    max_capital_per_trade_pct: 15,
    max_daily_loss_pct: 3,
    max_total_exposure_pct: 30,
    risk_per_trade_pct: 1,
    min_trade_value: 10000,
    max_trade_value: 50000,
    cooldown_minutes: 60,
    max_distance_from_or_pct: 1.0,
    brokerage_pct: 0.05,
    min_brokerage: 20,
    stt_pct: 0.001,
    exchange_pct: 0.0003,
    sebi_pct: 0.0001,
    stamp_pct: 0.0003,
    gst_pct: 0.18,
    created_at: "2024-01-03T00:00:00Z",
    updated_at: "2024-01-03T00:00:00Z",
  },
];

export const Empty: Story = {
  args: {
    strategies: [],
    templates: mockTemplates,
    onEdit: () => {},
    onDelete: () => {},
    isLoading: false,
  },
};

export const WithStrategies: Story = {
  args: {
    strategies: mockStrategies,
    templates: mockTemplates,
    onEdit: (strategy) => console.log("Edit:", strategy),
    onDelete: (strategyId) => console.log("Delete:", strategyId),
    isLoading: false,
  },
};

export const Loading: Story = {
  args: {
    strategies: [],
    templates: [],
    onEdit: () => {},
    onDelete: () => {},
    isLoading: true,
  },
};
